home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

ecole:
    resource: "@EcoleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
